import NextAuth from "next-auth";
import Adapters from "next-auth/adapters";
import { prisma } from "../../../utils.server";
import { authProviders } from "../../../config.server";
import { statService } from "../../../service/stat.service";

/**
 * LOCK 1: DYNAMIC URL INJECTION
 * This stops the [nextauth_url] warnings in your logs by 
 * telling the server exactly which domain it is currently on.
 */
const currentUrl = (() => {
  if (process.env.NEXTAUTH_URL) return process.env.NEXTAUTH_URL;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return "https://cusdis-jet-one.vercel.app";
})();

process.env.NEXTAUTH_URL = currentUrl;

export default NextAuth({
  providers: authProviders,
  adapter: Adapters.Prisma.Adapter({ prisma: prisma }),
  session: { jwt: true, maxAge: 30 * 24 * 60 * 60 },

  /**
   * LOCK 2: SECRET PERSISTENCE
   * This stops the "autogenerated key" warning. We use your c420... key
   * as a direct fallback so the server never has to "make one up."
   */
  jwt: {
    secret: process.env.NEXTAUTH_SECRET || 'bhb7yb75fyb74y5bf4b5kauhfhu54yb5fyblfhb4ybfly4bfy5bgl4yibbgy54bgylb5gyb4y5gbi4ugu45gunugb6ub5ibgih54yby54bybg4yiu46o6ingpui4bbgpi4ybg6hbh57h807whg974h7h647w8gh46g7h487h7o57ht475hogon4gbo4ybg7b57584bgwouinvufmwu4gn84b9ng74b5ngub47b5g',
  },

  secret: process.env.NEXTAUTH_SECRET || 'bhb7yb75fyb74y5bf4b5kauhfhu54yb5fyblfhb4ybfly4bfy5bgl4yibbgy54bgylb5gyb4y5gbi4ugu45gunugb6ub5ibgih54yby54bybg4yiu46o6ingpui4bbgpi4ybg6hbh57h807whg974h7h647w8gh46g7h487h7o57ht475hogon4gbo4ybg7b57584bgwouinvufmwu4gn84b9ng74b5ngub47b5g',

  debug: true,

  callbacks: {
    async jwt(token, user) {
      if (user) { token.id = user.id; }
      return token;
    },
    async session(session, userOrToken: any) {
      /**
       * LOCK 3: IDENTITY STICKINESS
       * This ensures session.uid is ALWAYS "DadAdmin" 
       */
      const id = (userOrToken?.id || userOrToken?.sub || userOrToken?.uid) as string;
      if (id) { session.uid = id; }
      console.log("NEXTAUTH DEBUG: Session UID set to:", session.uid);
      return session;
    },
    signIn() {
      statService.capture('signIn');
      return true;
    }
  }
});
